// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFhFRgvIXY72MI4EeHR2a_iFSPdKktsag',
    appId: '1:77989643764:android:534426c0050ee2ceeca5a1',
    messagingSenderId: '77989643764',
    projectId: 'dietlenz-38869',
    storageBucket: 'dietlenz-38869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPil9tHwFSkE1RsjYqQFsGrBCXpDotqgA',
    appId: '1:77989643764:ios:49277c091f40d953eca5a1',
    messagingSenderId: '77989643764',
    projectId: 'dietlenz-38869',
    storageBucket: 'dietlenz-38869.firebasestorage.app',
    androidClientId: '77989643764-2e8sr27tkt0a8qtdblj9kcj6u0182m92.apps.googleusercontent.com',
    iosClientId: '77989643764-r9d6s3bo54s474jli72loanuronr5fgr.apps.googleusercontent.com',
    iosBundleId: 'com.dietlenz.diet',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5sfiWP86Tzt-0MQLiblagejwX0aCuovE',
    appId: '1:77989643764:web:693ef7d7f7c81a9feca5a1',
    messagingSenderId: '77989643764',
    projectId: 'dietlenz-38869',
    authDomain: 'dietlenz-38869.firebaseapp.com',
    storageBucket: 'dietlenz-38869.firebasestorage.app',
    measurementId: 'G-HLFQ00EVH0',
  );

}